version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
    container_name: password_gen_api
    ports:
      - "9999:9999"
